# TCL File Generated by Component Editor 15.1
# Fri Apr 17 15:29:38 CST 2020
# DO NOT MODIFY


# 
# asi "asi" v1.0
# libing 2020.04.17.15:29:38
# Axi Slave Interface
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module asi
# 
set_module_property DESCRIPTION "Axi Slave Interface"
set_module_property NAME asi
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP asr_ai
set_module_property AUTHOR libing
set_module_property DISPLAY_NAME asi
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL asi
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file asi.sv SYSTEM_VERILOG PATH rtl/asi.sv TOP_LEVEL_FILE
add_fileset_file asi_r.sv SYSTEM_VERILOG PATH rtl/asi_r.sv
add_fileset_file asi_w.sv SYSTEM_VERILOG PATH rtl/asi_w.sv
add_fileset_file afifo.sv SYSTEM_VERILOG PATH rtl/afifo.sv


# 
# parameters
# 
add_parameter AXI_DW INTEGER 128
set_parameter_property AXI_DW DEFAULT_VALUE 128
set_parameter_property AXI_DW DISPLAY_NAME AXI_DW
set_parameter_property AXI_DW TYPE INTEGER
set_parameter_property AXI_DW UNITS None
set_parameter_property AXI_DW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_DW HDL_PARAMETER true
add_parameter AXI_AW INTEGER 32
set_parameter_property AXI_AW DEFAULT_VALUE 32
set_parameter_property AXI_AW DISPLAY_NAME AXI_AW
set_parameter_property AXI_AW TYPE INTEGER
set_parameter_property AXI_AW UNITS None
set_parameter_property AXI_AW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_AW HDL_PARAMETER true
add_parameter AXI_IW INTEGER 8
set_parameter_property AXI_IW DEFAULT_VALUE 8
set_parameter_property AXI_IW DISPLAY_NAME AXI_IW
set_parameter_property AXI_IW TYPE INTEGER
set_parameter_property AXI_IW UNITS None
set_parameter_property AXI_IW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_IW HDL_PARAMETER true
add_parameter AXI_LW INTEGER 8
set_parameter_property AXI_LW DEFAULT_VALUE 8
set_parameter_property AXI_LW DISPLAY_NAME AXI_LW
set_parameter_property AXI_LW TYPE INTEGER
set_parameter_property AXI_LW UNITS None
set_parameter_property AXI_LW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_LW HDL_PARAMETER true
add_parameter AXI_SW INTEGER 3
set_parameter_property AXI_SW DEFAULT_VALUE 3
set_parameter_property AXI_SW DISPLAY_NAME AXI_SW
set_parameter_property AXI_SW TYPE INTEGER
set_parameter_property AXI_SW UNITS None
set_parameter_property AXI_SW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_SW HDL_PARAMETER true
add_parameter AXI_BURSTW INTEGER 2
set_parameter_property AXI_BURSTW DEFAULT_VALUE 2
set_parameter_property AXI_BURSTW DISPLAY_NAME AXI_BURSTW
set_parameter_property AXI_BURSTW TYPE INTEGER
set_parameter_property AXI_BURSTW UNITS None
set_parameter_property AXI_BURSTW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_BURSTW HDL_PARAMETER true
add_parameter AXI_BRESPW INTEGER 2
set_parameter_property AXI_BRESPW DEFAULT_VALUE 2
set_parameter_property AXI_BRESPW DISPLAY_NAME AXI_BRESPW
set_parameter_property AXI_BRESPW TYPE INTEGER
set_parameter_property AXI_BRESPW UNITS None
set_parameter_property AXI_BRESPW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_BRESPW HDL_PARAMETER true
add_parameter AXI_RRESPW INTEGER 2
set_parameter_property AXI_RRESPW DEFAULT_VALUE 2
set_parameter_property AXI_RRESPW DISPLAY_NAME AXI_RRESPW
set_parameter_property AXI_RRESPW TYPE INTEGER
set_parameter_property AXI_RRESPW UNITS None
set_parameter_property AXI_RRESPW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AXI_RRESPW HDL_PARAMETER true
add_parameter ASI_AD INTEGER 16
set_parameter_property ASI_AD DEFAULT_VALUE 16
set_parameter_property ASI_AD DISPLAY_NAME ASI_AD
set_parameter_property ASI_AD TYPE INTEGER
set_parameter_property ASI_AD UNITS None
set_parameter_property ASI_AD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ASI_AD HDL_PARAMETER true
add_parameter ASI_RD INTEGER 16
set_parameter_property ASI_RD DEFAULT_VALUE 16
set_parameter_property ASI_RD DISPLAY_NAME ASI_RD
set_parameter_property ASI_RD TYPE INTEGER
set_parameter_property ASI_RD UNITS None
set_parameter_property ASI_RD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ASI_RD HDL_PARAMETER true
add_parameter ASI_WD INTEGER 16
set_parameter_property ASI_WD DEFAULT_VALUE 16
set_parameter_property ASI_WD DISPLAY_NAME ASI_WD
set_parameter_property ASI_WD TYPE INTEGER
set_parameter_property ASI_WD UNITS None
set_parameter_property ASI_WD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ASI_WD HDL_PARAMETER true
add_parameter ASI_BD INTEGER 16
set_parameter_property ASI_BD DEFAULT_VALUE 16
set_parameter_property ASI_BD DISPLAY_NAME ASI_BD
set_parameter_property ASI_BD TYPE INTEGER
set_parameter_property ASI_BD UNITS None
set_parameter_property ASI_BD ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ASI_BD HDL_PARAMETER true
add_parameter ASI_ARB INTEGER 0
set_parameter_property ASI_ARB DEFAULT_VALUE 0
set_parameter_property ASI_ARB DISPLAY_NAME ASI_ARB
set_parameter_property ASI_ARB TYPE INTEGER
set_parameter_property ASI_ARB UNITS None
set_parameter_property ASI_ARB ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ASI_ARB HDL_PARAMETER true
add_parameter SLV_WS INTEGER 1
set_parameter_property SLV_WS DEFAULT_VALUE 1
set_parameter_property SLV_WS DISPLAY_NAME SLV_WS
set_parameter_property SLV_WS TYPE INTEGER
set_parameter_property SLV_WS UNITS None
set_parameter_property SLV_WS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SLV_WS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point altera_axi4_slave
# 
add_interface altera_axi4_slave axi4 end
set_interface_property altera_axi4_slave associatedClock axi_clock_sink
set_interface_property altera_axi4_slave associatedReset axi_reset_sink
set_interface_property altera_axi4_slave readAcceptanceCapability 1
set_interface_property altera_axi4_slave writeAcceptanceCapability 1
set_interface_property altera_axi4_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4_slave readDataReorderingDepth 1
set_interface_property altera_axi4_slave bridgesToMaster ""
set_interface_property altera_axi4_slave ENABLED true
set_interface_property altera_axi4_slave EXPORT_OF ""
set_interface_property altera_axi4_slave PORT_NAME_MAP ""
set_interface_property altera_axi4_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_slave AWID awid Input AXI_IW
add_interface_port altera_axi4_slave AWADDR awaddr Input AXI_AW
add_interface_port altera_axi4_slave AWLEN awlen Input AXI_LW
add_interface_port altera_axi4_slave AWSIZE awsize Input AXI_SW
add_interface_port altera_axi4_slave AWBURST awburst Input AXI_BURSTW
add_interface_port altera_axi4_slave AWVALID awvalid Input 1
add_interface_port altera_axi4_slave AWREADY awready Output 1
add_interface_port altera_axi4_slave AWLOCK awlock Input 1
add_interface_port altera_axi4_slave AWCACHE awcache Input 4
add_interface_port altera_axi4_slave AWPROT awprot Input 3
add_interface_port altera_axi4_slave AWQOS awqos Input 4
add_interface_port altera_axi4_slave AWREGION awregion Input 4
add_interface_port altera_axi4_slave WDATA wdata Input AXI_DW
add_interface_port altera_axi4_slave WSTRB wstrb Input 16
add_interface_port altera_axi4_slave WLAST wlast Input 1
add_interface_port altera_axi4_slave WVALID wvalid Input 1
add_interface_port altera_axi4_slave WREADY wready Output 1
add_interface_port altera_axi4_slave BID bid Output AXI_IW
add_interface_port altera_axi4_slave BRESP bresp Output AXI_BRESPW
add_interface_port altera_axi4_slave BVALID bvalid Output 1
add_interface_port altera_axi4_slave BREADY bready Input 1
add_interface_port altera_axi4_slave ARID arid Input AXI_IW
add_interface_port altera_axi4_slave ARADDR araddr Input AXI_AW
add_interface_port altera_axi4_slave ARLEN arlen Input AXI_LW
add_interface_port altera_axi4_slave ARSIZE arsize Input AXI_SW
add_interface_port altera_axi4_slave ARBURST arburst Input AXI_BURSTW
add_interface_port altera_axi4_slave ARVALID arvalid Input 1
add_interface_port altera_axi4_slave ARREADY arready Output 1
add_interface_port altera_axi4_slave ARLOCK arlock Input 1
add_interface_port altera_axi4_slave ARCACHE arcache Input 4
add_interface_port altera_axi4_slave ARPROT arprot Input 3
add_interface_port altera_axi4_slave ARQOS arqos Input 4
add_interface_port altera_axi4_slave ARREGION arregion Input 4
add_interface_port altera_axi4_slave RID rid Output AXI_IW
add_interface_port altera_axi4_slave RDATA rdata Output AXI_DW
add_interface_port altera_axi4_slave RRESP rresp Output AXI_RRESPW
add_interface_port altera_axi4_slave RLAST rlast Output 1
add_interface_port altera_axi4_slave RVALID rvalid Output 1
add_interface_port altera_axi4_slave RREADY rready Input 1


# 
# connection point axi_clock_sink
# 
add_interface axi_clock_sink clock end
set_interface_property axi_clock_sink clockRate 0
set_interface_property axi_clock_sink ENABLED true
set_interface_property axi_clock_sink EXPORT_OF ""
set_interface_property axi_clock_sink PORT_NAME_MAP ""
set_interface_property axi_clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property axi_clock_sink SVD_ADDRESS_GROUP ""

add_interface_port axi_clock_sink ACLK clk Input 1


# 
# connection point axi_reset_sink
# 
add_interface axi_reset_sink reset end
set_interface_property axi_reset_sink associatedClock axi_clock_sink
set_interface_property axi_reset_sink synchronousEdges DEASSERT
set_interface_property axi_reset_sink ENABLED true
set_interface_property axi_reset_sink EXPORT_OF ""
set_interface_property axi_reset_sink PORT_NAME_MAP ""
set_interface_property axi_reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property axi_reset_sink SVD_ADDRESS_GROUP ""

add_interface_port axi_reset_sink ARESETn reset_n Input 1


# 
# connection point ram_clock_sink
# 
add_interface ram_clock_sink clock end
set_interface_property ram_clock_sink clockRate 0
set_interface_property ram_clock_sink ENABLED true
set_interface_property ram_clock_sink EXPORT_OF ""
set_interface_property ram_clock_sink PORT_NAME_MAP ""
set_interface_property ram_clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property ram_clock_sink SVD_ADDRESS_GROUP ""

add_interface_port ram_clock_sink RAM_CLK clk Input 1


# 
# connection point ram_reset_sink
# 
add_interface ram_reset_sink reset end
set_interface_property ram_reset_sink associatedClock ram_clock_sink
set_interface_property ram_reset_sink synchronousEdges DEASSERT
set_interface_property ram_reset_sink ENABLED true
set_interface_property ram_reset_sink EXPORT_OF ""
set_interface_property ram_reset_sink PORT_NAME_MAP ""
set_interface_property ram_reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property ram_reset_sink SVD_ADDRESS_GROUP ""

add_interface_port ram_reset_sink RAM_RESETn reset_n Input 1


# 
# connection point ram_io
# 
add_interface ram_io conduit end
set_interface_property ram_io associatedClock ram_clock_sink
set_interface_property ram_io associatedReset ram_reset_sink
set_interface_property ram_io ENABLED true
set_interface_property ram_io EXPORT_OF ""
set_interface_property ram_io PORT_NAME_MAP ""
set_interface_property ram_io CMSIS_SVD_VARIABLES ""
set_interface_property ram_io SVD_ADDRESS_GROUP ""

add_interface_port ram_io RAM_A addr Output AXI_AW
add_interface_port ram_io RAM_CEN cen Output 1
add_interface_port ram_io RAM_D wdata Output AXI_DW
add_interface_port ram_io RAM_Q rdata Input AXI_DW
add_interface_port ram_io RAM_WEN wen Output 16

